# Generated by Django 3.1.6 on 2021-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_API', '0003_auto_20210511_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Decides if the user is active', verbose_name='Active'),
        ),
    ]
